name: CTVC Daily Scraper

on:
  schedule:
    # Runs at 00:15 UTC every day
    - cron: '15 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-ctvc:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run CTVC scraper (v2 - New Schema)
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        echo "🚀 Starting CTVC scraper v2 (New Schema) at $(date)"
        python scrape_ctvc_daily_v2.py
        echo "✅ CTVC scraper v2 completed at $(date)"
